name: Update GIFs JSON

on:
  push:
    branches:
      - main
    paths:
      - 'gifs/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate gifs.json
      run: |
        echo "[" > gifs.json
        ls gifs/*.gif 2>/dev/null | sed 's|gifs/||' | sort | awk '{printf "\"%s\",",$0}' >> gifs.json
        sed -i 's/,$/]/' gifs.json
    - name: Commit gifs.json
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add gifs.json
        git diff-index --quiet HEAD || git commit -m "Update gifs.json"
        git push https://$PAT_TOKEN@github.com/KhawerAbbas7/MyGifs HEAD:main
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

