name: Update GIFs JSON

on:
  push:
    branches:
      - main
    paths:
      - 'gifs/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for the default GITHUB_TOKEN to push
    steps:
      - uses: actions/checkout@v3

      - name: Generate gifs.json
        shell: python
        run: |
          import os, json
          files = [f for f in os.listdir('public/gifs') if f.endswith('.gif')]
          files.sort()
          with open('gifs.json', 'w') as f:
            json.dump(files, f)

      - name: Commit gifs.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gifs.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update gifs.json [skip ci]"
            git pull --rebase origin main
            git push
          fi

